---
title: '**Law of Large Numbers**'
subtitle: "Mini-Assignment 2022-11-29 - MTH 461 - Fall 2022"
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[RO,R]{MTH 461A - Fall 2022}
  \fancyfoot[CO,C]{}
  \fancyfoot[R]{\thepage}
  \usepackage{float}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
    keep_tex: true
urlcolor: blue
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\

**Instructions:**
 
 * Please provide complete solutions for each problem. If it involves mathematical computations, explanations, or analysis, please provide your reasoning or detailed solutions.
 
 * Note that some problems have multiple solutions or ways to solve it. Make sure that your solutions are clear enough to showcase your work and understanding of the material.
 
 * Creativity and collaborations are encouraged. Use all of the resources you have and what you need to complete the mini-assignment. Each student must take personal responsibility and submit their work individually. Please abide by the University of Portland Academic Honor Principle.
 
 * There are two ways you can write your answers, a: by handwriting (either physically or digitally), or b: by typing on a template document with file type options, which can be downloaded from the course website.
 
 * If you had handwritten your answers/solutions on a physical paper, make sure to label it properly and please scan your document using a scanner app for convenience. Suggestions: (1) ["Tiny Scanner" for Android](https://play.google.com/store/apps/details?id=com.appxy.tinyscanner&hl=en_US&gl=US){target="_blank"} or (2) ["Scanner App" for iOS](https://apps.apple.com/us/app/scanner-app-scan-pdf-document/id595563753){target="_blank"}.
 
 * **Please save your work as one pdf file, don't put your name in any part of the document, and submit it to the Teams Assignments for this course. Your document upload will correspond to your name automatically in Teams.**
 
 * If you have questions or concerns, please feel free to ask the instructor.

\newpage
  
1. Suppose you are simulating an unfair n-sided dice where it is more in favor to land on even numbers.

    a. Write a probability mass function of the unfair n-sided dice assuming that the even numbers have equal probability, and the odd numbers have also equal probability. Your pmf shoud have $n$ as a parameter for the number of sides and $p$ as the probability of landing an even number.
    b. What is the expected value?
    c. Modify the R script `loln.R` to simulate the dice rolling and provide the plot you generated. Describe your observations of your plot in terms of the law of large numbers.

2.  Use the Monte Carlo Integration method to show the results of the Gaussian Integral (written below) to be $\sqrt{\pi}$.
$$\int_{-\infty}^{\infty} e^{-x^2}\,dx = \sqrt{\pi}$$

    Modify the R script `moi.R` to use the Monte Carlo Integration method. Since you have an improper integral, you can set the integral bounds to be $[-5,5]$ to approximate the integral. You may need to increase the number samples in your Monte Carlo simulation. Is your approximation close to $\sqrt{\pi}$? Use the law of Large Numbers to explain your results.
    