---
title: "**Welcome!** <br><br> **MTH 461: Probability and Statistics I**"
subtitle: "Fall 2022 - University of Portland"
---

<br>

## **Quick Content Guide**

| Page                                         | Contents                                                                             |
|----------------------------------------------|--------------------------------------------------------------------------------------|
| [Home](index.html)          | -                                                                                    |
| [Syllabus](syllabus.html)   | About the class, class materials and resources, class assessment and expectations |
| [Topics](topics.html) | Tentative topics, notes, assignments, and books and online resources list        |
| [Mini-Projects](mini-projects.html)         | Mini-project information and expectations                                           |

<br>

## **Quick Facts**

<br>

### Instructor Information

  * **Instructor:** [Alex John Quijano](https://www.alexjohnquijano.com/){target="_blank"} <br>
  * **Office:** Buckley Center 279 <br>
  * **Email:** quijano@up.edu <br>

<br>

### Class Time and Location

  * **Lectures:** TuTh 2:30 PM – 3:55 PM <br>
  * **Rooms:** Franz Hall 128 <br>

<br>

### Office Hours

* Alex John Quijano
  * Walk-in (Buckley Center 279)
    * MWF, 1:00 PM -  2:00 PM
    * TuTh, 4:00 PM - 5:00 PM
  * One-to-One (Buckley Center 279 or in Teams)
    * MWF, 2:00 PM - 5:00 PM ([sign-up for a 30-minute session](https://calendly.com/alexjohnquijano/quijano-fa22-scheduled-office-hours){target="_blank"})

<br>

## **Quick Resources**

<br>

### Textbook

The main textbook is [Probability, Statistics, and Data: A fresh approach using R](https://mathstat.slu.edu/~speegle/_book/){target="_blank"} by Darrin Speegle and Bryan Clair. The textbook is free and open-source. We will also use other supplementary books and resources throughout the course (please see the [Topics Schedule](topics.html)).

<br>

### Computing

This class will use the R programming language and the R Studio Integrated Development Environment (IDE). There are several ways to use R and R Studio. Below are two ways to access R and R Studio.

* *Clark Library Digital labs.* On campus, there are two computer labs that are located in Shiley Hall room 208 and the Clark Library. When you log-in into the lab computers using your UP credentials, you will have access to R (The availability of R Studio is still unknown; pending confirmation).

* *Downloading and Installing on your own computer.* First, you need to install R; [r-project.org](https://www.r-project.org/){target="_blank"}. Next, you can install R Studio; [rstudio download](https://www.rstudio.com/products/rstudio/download/){target="_blank"}.

If you need a computer, you can borrow computers - please see the [Clark Library Laptop Borrowing](https://library.up.edu/services/laptops.html){target="_blank"} webpage. For more information and resources, visit the [Clark Library Student Services](https://library.up.edu/services/services-students.html){target="_blank"}.

<br>

### Microsoft Teams

We will be using Teams [MTH-461A-fa22](https://teams.microsoft.com/l/team/19%3aZWmNLgAQL0Vt__PZ2qLdmGNPJB0r6ChJXXVf2lzsT-E1%40thread.tacv2/conversations?groupId=e41b3e0c-9f5c-4496-a6a4-e51b0941d10e&tenantId=ea8f3949-231c-40b6-a33f-56873af96f87){target="_blank"} as the main real-time communication tool for general announcements, assignment submissions, question-answering discussions, and direct messages. <span style="color:red">Please signup for the course Teams using your UP credentials along with this Teams code: **rg9ngv0**.</span>

<span style="color:red">Please check the class Teams regularly.</span> If you need to have Teams notifications sent to your email, please set up your email preferences within Teams.

<span style="color:red">If you prefer communicating through email, note that I had has set up an email filter for this course and you must put the “MTH 461” keyword in your subject line.</span> It is easy for me to get notice of your email if you put the keyword in the subject line. Concise and specific messages are helpful so I know how I can best help you.

<br>
