---
title: '**Tentative Topics Schedule**'
subtitle: "Fall 2022 - University of Portland"
---

<br>

<center>**- See Books & Online Resources List for the reading materials -**</center>
<center><span style="color:red">**The readings are not mandatory but it is encouraged.**</span></center>
<center><span style="color:red">**Lecture slides and Mini-Assignments will be available the day before class.**</span></center>
<center><span style="color:red">**Modules will be available two weeks before the deadline.**</span></center>

<br>

The "Reading" column in the table below contains a number on which it refers to a numbered item in the Books & Online Resources List. For example "[PSDR]" refers to the first item in the list, which is our main text book titled "Probability, Statistics, and Data: A fresh approach using R". 

<br>

## **Topics and Reading Materials**

<br>

| **Day** |                 **Topic**                 |      **Pre-Reading [PSDR]**     | **Post-Reading [PSDR]** | **Mini-Assignment** | **Deadline** |
|:-------:|:-----------------------------------------:|:-------------------------------:|:-----------------------:|:-------------------:|:------------:|
|   8/30  |       [Orientation \& Calculus Review](topics/20220830/orientation-and-calculus-review.html)      |             Syllabus            |            -            |         [[pdf](topics/20220830/ma-mth461a-20220830.pdf){target="_blank"}] [[Rmd](topics/20220830/ma-mth461a-20220830.Rmd){target="_blank"}] [[tex](topics/20220830/ma-mth461a-20220830.tex){target="_blank"}]         |     8/31     |
|   9/1   |    [Basics of Probability Theory Part 1](topics/20220901/basics-of-probability-theory-part-1.html)    |    Ch. 2 (Preamble), Ch. 2.1    |            -            |         [[pdf](topics/20220901/ma-mth461a-20220901.pdf){target="_blank"}] [[Rmd](topics/20220901/ma-mth461a-20220901.Rmd){target="_blank"}] [[tex](topics/20220901/ma-mth461a-20220901.tex){target="_blank"}]         |      9/1     |
|   9/6   |    [Basics of Probability Theory Part 2](topics/20220906/basics-of-probability-theory-part-2.html)    |     Ch. 2.1 Cont. \& Ch. 2.4    |         Ch. 2.2         |         [[pdf](topics/20220906/ma-mth461a-20220906.pdf){target="_blank"}] [[Rmd](topics/20220906/ma-mth461a-20220906.Rmd){target="_blank"}] [[tex](topics/20220906/ma-mth461a-20220906.tex){target="_blank"}]         |      9/6     |
|   9/8   |  [Independence \& Conditional Probability](topics/20220908/independence-and-conditional-probability.html)  | Ch. 2.3 (Preamble) \& Ch. 2.3.1 |            -            |         [[pdf](topics/20220908/ma-mth461a-20220908.pdf){target="_blank"}] [[Rmd](topics/20220908/ma-mth461a-20220908.Rmd){target="_blank"}] [[tex](topics/20220908/ma-mth461a-20220908.tex){target="_blank"}]         |      9/8     |
|    \|    |      Introduction to R \& R Markdown      |    Ch. 1                        |            -            |          -          |       -       |
|  **-**  |              **Module 1 Due**             |              **-**              |          **-**          |        [[pdf](modules/module-1/module-1-mth461-fall2022.pdf){target="_blank"}] [[zip](modules/module-1/module-1-mth461-fall2022.zip){target="_blank"}]        |    **9/13**   |
|   9/13  |               [Bayes Theorem](topics/20220913/bayes-theorem.html)               |            Ch. 2.3.3            |            -            |         [[pdf](topics/20220913/ma-mth461a-20220913.pdf){target="_blank"}] [[Rmd](topics/20220913/ma-mth461a-20220913.Rmd){target="_blank"}] [[tex](topics/20220913/ma-mth461a-20220913.tex){target="_blank"}]         |     9/13     |
|   9/15  | [Random Variables \& Probability Functions](topics/20220915/random-variables-and-probability-functions.html) |                -                |            -            |         [[pdf](topics/20220915/ma-mth461a-20220915.pdf){target="_blank"}] [[Rmd](topics/20220915/ma-mth461a-20220915.Rmd){target="_blank"}] [[tex](topics/20220915/ma-mth461a-20220915.tex){target="_blank"}]         |     9/15     |
|   9/20  |      [Discrete Random Variables (DRVs)](topics/20220920/discrete-random-variables.html)     |         Ch. 3 (Preamble)        |            -            |         [[pdf](topics/20220920/ma-mth461a-20220920.pdf){target="_blank"}] [[Rmd](topics/20220920/ma-mth461a-20220920.Rmd){target="_blank"}] [[tex](topics/20220920/ma-mth461a-20220920.tex){target="_blank"}]         |     9/20     |
|   9/22  |         [Probability Mass Functions](topics/20220922/probability-mass-functions.html)        |             Ch. 3.1             |            -            |         [[pdf](topics/20220922/ma-mth461a-20220922.pdf){target="_blank"}] [[Rmd](topics/20220922/ma-mth461a-20220922.Rmd){target="_blank"}] [[tex](topics/20220922/ma-mth461a-20220922.tex){target="_blank"}]         |     9/22     |
|   9/27  |          [Expected Values for DRVs](topics/20220927/expected-values-for-drvs.html)         |             Ch. 3.2             |            -            |         [[pdf](topics/20220927/ma-mth461a-20220927.pdf){target="_blank"}] [[Rmd](topics/20220927/ma-mth461a-20220927.Rmd){target="_blank"}] [[tex](topics/20220927/ma-mth461a-20220927.tex){target="_blank"}]         |     9/27     |
|   9/29  |        -        |             -             |            -            |         -         |     9/29     |
|   10/4  |         [Moment Generating Functions for DRVs](topics/20221004/moment-generating-functions-for-drvs.html)            |             Ch. 3.4             |            -            |         [[pdf](topics/20221004/ma-mth461a-20221004.pdf){target="_blank"}] [[Rmd](topics/20221004/ma-mth461a-20221004.Rmd){target="_blank"}] [[tex](topics/20221004/ma-mth461a-20221004.tex){target="_blank"}]         |     10/4     |
|   10/6  |     [Variance for DRVs](topics/20221006/variance-for-drvs.html)    |          Ch. 3.5          |            -            |         [[pdf](topics/20221006/ma-mth461a-20221006.pdf){target="_blank"}] [[Rmd](topics/20221006/ma-mth461a-20221006.Rmd){target="_blank"}] [[tex](topics/20221006/ma-mth461a-20221006.tex){target="_blank"}]         |     10/6     |
|  10/11  |         [Covariance and Correlation for DRVs](topics/20221011/covariance-and-correlation-for-drvs.html)         |            Ch. 3.5 Cont.            |            Ch. 3.6            |         [[pdf](topics/20221011/ma-mth461a-20221011.pdf){target="_blank"}] [[Rmd](topics/20221011/ma-mth461a-20221011.Rmd){target="_blank"}] [[tex](topics/20221011/ma-mth461a-20221011.tex){target="_blank"}]         |     10/11    |
|  10/13  |        -         |             -            |         -         |         -         |     10/13    |
|   _-_   |              _Fall Vacation_              |               _-_               |           _-_           |         _-_         |      _-_     |
|  10/25  |                   [Continuous Random Variables (CRVs)](notes/continuous-random-variables-for-crvs.pdf){target="_blank"}}                 |                -                |            -            |          [[pdf](topics/20221025/ma-mth461a-20221025.pdf){target="_blank"}] [[Rmd](topics/20221025/ma-mth461a-20221025.Rmd){target="_blank"}] [[tex](topics/20221025/ma-mth461a-20221025.tex){target="_blank"}]          |       10/25      |
|  10/27  |     Joint \& Marginal Distributions for CRVs    |               -               |           -           |         [[pdf](topics/20221027/ma-mth461a-20221027.pdf){target="_blank"}] [[Rmd](topics/20221027/ma-mth461a-20221027.Rmd){target="_blank"}] [[tex](topics/20221027/ma-mth461a-20221027.tex){target="_blank"}]         |     10/27    |
|   11/1  |       [Covariance \& Correlation for CRVs](notes/covariance-and-correlation-for-crvs.pdf){target="_blank"}       |               -               |           -           |         [[pdf](topics/20221101/ma-mth461a-20221101.pdf){target="_blank"}] [[Rmd](topics/20221101/ma-mth461a-20221101.Rmd){target="_blank"}] [[tex](topics/20221101/ma-mth461a-20221101.tex){target="_blank"}]         |     11/1     |
|   11/3  |   Conditioning and Independence for CRVs    |               -               |           -           |         TBA         |     11/3     |
|   11/8  |  Moment Generating Functions for CRVs  |               -               |           -           |         TBA         |     11/8     |
|  11/10  |     Exponential Random Variables    |               -               |           -           |         TBA         |     11/10    |
|  11/15  |        Normal Random Variables       |               -               |           -           |         TBA         |     11/15    |
|  11/17  |          Advanced R \& R Markdown          |               -               |           -           |         TBA         |     11/17    |
|  11/22  |            Simulations of Random Variables           |               -               |           -           |         TBA         |     11/22    |
|   _-_   |          _Thanksgiving Vacation_          |               _-_               |           _-_           |         _-_         |      _-_     |
|  11/29  |          The Law of Large Numbers         |               TBA               |           TBA           |         TBA         |     11/29    |
|   12/1  |         The Central Limit Theorem         |               TBA               |           TBA           |         TBA         |     12/1     |
|   12/6  |              Point Estimators             |               TBA               |           TBA           |         TBA         |     12/6     |
|   12/8  |       Maximum Likelihood Estimation       |               TBA               |           TBA           |         TBA         |     12/8     |
|  **-**  |              **Module 2 Due**             |              **-**              |          **-**          |        **-**        |   **12/9**   |
|  **-**  |           **Mini-Project Due**          |              **-**              |          **-**          |        **-**        |   **12/15**  |

<br>

## **Books & Online Resources Lists**

<br>

### Main Textbook

[PSDR]   [Speegle, D., & Clair, B. (2021). Probability, Statistics, and Data: A Fresh Approach Using R. Chapman and Hall/CRC.](https://mathstat.slu.edu/~speegle/_book/){target="_blank"}

<br>

### Supplementary Textbook

[IPSR]   [Pishro-Nik, H. (2016). Introduction to probability, statistics, and random processes.](https://www.probabilitycourse.com/){target="_blank"}

<br>