---
title: '**Simulations of Random Variables Using R**'
subtitle: "Mini-Assignment 2022-11-22 - MTH 461 - Fall 2022"
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[RO,R]{MTH 461A - Fall 2022}
  \fancyfoot[CO,C]{}
  \fancyfoot[R]{\thepage}
  \usepackage{float}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
    keep_tex: true
urlcolor: blue
link-citations: yes
bibliography: references.bib
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\

**Instructions:**
 
 * Please provide complete solutions for each problem. If it involves mathematical computations, explanations, or analysis, please provide your reasoning or detailed solutions.
 
 * Note that some problems have multiple solutions or ways to solve it. Make sure that your solutions are clear enough to showcase your work and understanding of the material.
 
 * Creativity and collaborations are encouraged. Use all of the resources you have and what you need to complete the mini-assignment. Each student must take personal responsibility and submit their work individually. Please abide by the University of Portland Academic Honor Principle.
 
 * There are two ways you can write your answers, a: by handwriting (either physically or digitally), or b: by typing on a template document with file type options, which can be downloaded from the course website.
 
 * If you had handwritten your answers/solutions on a physical paper, make sure to label it properly and please scan your document using a scanner app for convenience. Suggestions: (1) ["Tiny Scanner" for Android](https://play.google.com/store/apps/details?id=com.appxy.tinyscanner&hl=en_US&gl=US){target="_blank"} or (2) ["Scanner App" for iOS](https://apps.apple.com/us/app/scanner-app-scan-pdf-document/id595563753){target="_blank"}.
 
 * **Please save your work as one pdf file, don't put your name in any part of the document, and submit it to the Teams Assignments for this course. Your document upload will correspond to your name automatically in Teams.**
 
 * If you have questions or concerns, please feel free to ask the instructor.

\newpage
  
1. Let $X$ be a uniformly distributed random variable on the interval $[0,1]$. You will consider the CDF and PDF of $Y = X^{3}$.

    a. Determine the CDF and PDF of $Y$ by hand.
    b. Modify the R code (lines: 15, 29, 36, 40 \& 58) you were given to:
        - generate samples of $X$, samples of $Y$ 
        - create histograms of both $X$ and $Y$
        - annotate those histograms (as in the sample code) with the true PDF in red.

    Let $F_X$ and $f_X$ be the CDF and PDF of $X$ respectively. Note that a uniformly distributed random variable $X$ on the interval $[0,1]$ has a PDF and CDF 
  $$f_X(x) = 1 \text{ and } F_X = \begin{cases}
  0 & x < 0, \\
  x & 0 \leq x \leq 1, \\
  1 & 1 < x
  \end{cases}
  $$

2. Let $X_1,X_2, \text{ and } X_3$ be a independently generated uniformly distributed random variable on the interval $[0,1]$. You will consider the CDF and PDF of $Y = \max \{ X_1, X_2, X_3 \}$.

    a. Determine the CDF and PDF of $Y$ by hand.
    b. Modify the R code (lines: 82, 97, 101 \& 119) you were given to:
        - generate samples of $X_1,X_2, \text{ and } X_3$, samples of $Y$ 
        - create histograms of one of the $X_i$ and $Y$
        - annotate those histograms (as in the sample code) with the true PDF in red.

    Note that the CDF of $Y$ can be written as
    \begin{align*}
    F_Y(y) = P(Y \leq y ) & = & P\left( \max \{ X_1, X_2, X_3 \} \leq y\right) \\
                          & = & P( X_1 \leq y \text{ and } X_2 \leq y \text{ and } X_3 \leq y).
    \end{align*}
    The first line comes from the definition of the CDF, where the second line comes from the definition of maximum. Because $X_1, X_2$ and $X_3$ are independent and have the same distribution we have,
    $$F_Y(y)=P( X_1 \leq y \text{ and } X_2 \leq y \text{ and } X_3 \leq y) =  \prod_{i = 1}^{3} P(X_i \leq y) = \left( F_X(y) \right)^3.$$
