---
title: "Independence and Conditional Probability"
output:
  slidy_presentation:
    font_adjustment: 4
date: "2022-09-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Previously (Part 1/2)...

**Independence**

**[PSDR] Definition 2.20**

Two events are said to be *independent* if knowledge that one event occurs does not give any probabilistic information as to whether the other event occurs. Formally, we say that $A$ and $B$ are independent if $P(A \cap B) = P(A)P(B)$.

Events $A$ and $B$ are said to be dependent if they are not independent.

## Previously (Part 2/2)...

**Sampling WITH or WITHOUT replacement**

* **Sampling WITH replacement:** A method of sampling that an *item is sampled more than once*. Sampling with replacement generally produces *independent events*. Usually scenarios - but not always - like this does not distinguish identical items. 

* **Sampling WITHOUT replacement:** A method of sampling where an *item may not be sampled more than once*. Sampling without replacement generally produce *dependent events*. Usually - but not always - scenarios like this does distinguish identical items.

## Conditional Probabability

**[PSDR] Definition 2.18**

Let $A$ and $B$ be events in the sample space $S$, with $P(B) \ne 0$. The conditional probability of $A$ given $B$ is 
$$P(A|B) = \frac{P(A \cap B)}{P(B)}$$

**[PSDR] Proposition 2.1**

Two simple facts about conditional probability are:

  1. $P((A \cap B) | B) = P(A|B)$.
  2. $P(A \cup B | B ) = 1$.
  
## Independence and Conditional Probability  
  
**[PSDR] Theorem 2.3**

Let $A$ and $B$ be events with non-zero probability in the sample space $S$. The following are equivalent:

  1. $A$ and $B$ are independent.
  2. $P(A \cap B) = P(A)P(B)$.
  3. $P(A|B) = P(A)$.
  4. $P(B|A) = P(B)$.

## Simple Example Problem

Consider a scenario where you draw three balls from an urn without replacement. The urn has 6 balls in total; 2 reds and 4 black.

What is the probability that at least two black balls are drawn?

## Mini-Activity

[Mini-Assignment: Independence and Conditional Probability](ma-mth461a-20220908.pdf){target="_blank"}

Back to [Tentative Topics Schedule](../../topics.html).
