---
title: '**Bayes Theorem**'
subtitle: "Mini-Assignment 2022-09-13 - MTH 461 - Fall 2022"
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[RO,R]{MTH 461A - Fall 2022}
  \fancyfoot[CO,C]{}
  \fancyfoot[R]{\thepage}
  \usepackage{float}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
    keep_tex: true
urlcolor: blue
link-citations: yes
bibliography: references.bib
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\

**Instructions:**
 
 * Please provide complete solutions for each problem. If it involves mathematical computations, explanations, or analysis, please provide your reasoning or detailed solutions.
 
 * Note that some problems have multiple solutions or ways to solve it. Make sure that your solutions are clear enough to showcase your work and understanding of the material.
 
 * Creativity and collaborations are encouraged. Use all of the resources you have and what you need to complete the mini-assignment. Each student must take personal responsibility and submit their work individually. Please abide by the University of Portland Academic Honor Principle.
 
 * There are two ways you can write your answers, a: by handwriting (either physically or digitally), or b: by typing on a template document with file type options, which can be downloaded from the course website.
 
 * If you had handwritten your answers/solutions on a physical paper, make sure to label it properly and please scan your document using a scanner app for convenience. Suggestions: (1) ["Tiny Scanner" for Android](https://play.google.com/store/apps/details?id=com.appxy.tinyscanner&hl=en_US&gl=US){target="_blank"} or (2) ["Scanner App" for iOS](https://apps.apple.com/us/app/scanner-app-scan-pdf-document/id595563753){target="_blank"}.
 
 * **Please save your work as one pdf file, don't put your name in any part of the document, and submit it to the Teams Assignments for this course. Your document upload will correspond to your name automatically in Teams.**
 
 * If you have questions or concerns, please feel free to ask the instructor.

\newpage

1. Consider a scenario where you have *two* urns with contents shown in a table below. One urn is chosen at random and *three* balls are selected. 

    a. If two balls are red, what is the probability that it came from Urn 1?
    b. If the balls are two reds and one black, what is the probability that it came from Urn 1?

<center>
|       | **Red** | **Black** |
|:-------:|:-----:|:-------:|
| **Urn 1** | 3   | 3     |
| **Urn 2** | 4   | 2     |
</center>

    
2. Consider a scenario where you draw $three$ cards from $two$ standard decks shuffled together. Note that the two decks can be distinguishable but you won't be able to distinguish them when drawing.

    a. If you have all three queens, what is the probability that they all came from the same deck?
    b. If you have two kings and one queen, what is the probability that they all came from the same deck?

\

(Hint for problems 1 and 2: Use the counting arguments method when you apply Bayes' Theorem and the law of total probability. Visualizing using a forward and backward tree is also useful.)
    