---
title: '**Probability Theory Basics Part 1**'
subtitle: "Mini-Assignment 2022-08-30 - MTH 461 - Fall 2022"
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[RO,R]{MTH 461A - Fall 2022}
  \fancyfoot[CO,C]{}
  \fancyfoot[R]{\thepage}
  \usepackage{float}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
    keep_tex: true
urlcolor: blue
link-citations: yes
bibliography: references.bib
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\

**Instructions:**
 
 * Please provide complete solutions for each problem. If it involves mathematical computations, explanations, or analysis, please provide your reasoning or detailed solutions.
 
 * Note that some problems have multiple solutions or ways to solve it. Make sure that your solutions are clear enough to showcase your work and understanding of the material.
 
 * Creativity and collaborations are encouraged. Use all of the resources you have and what you need to complete the mini-assignment. Each student must take personal responsibility and submit their work individually. Please abide by the University of Portland Academic Honor Principle.
 
 * There are two ways you can write your answers, a: by handwriting (either physically or digitally), or b: by typing on a template document with file type options, which can be downloaded from the course website.
 
 * If you had handwritten your answers/solutions on a physical paper, make sure to label it properly and please scan your document using a scanner app for convenience. Suggestions: (1) ["Tiny Scanner" for Android](https://play.google.com/store/apps/details?id=com.appxy.tinyscanner&hl=en_US&gl=US){target="_blank"} or (2) ["Scanner App" for iOS](https://apps.apple.com/us/app/scanner-app-scan-pdf-document/id595563753){target="_blank"}.
 
 * **Please save your work as one pdf file, don't put your name in any part of the document, and submit it to the Teams Assignments for this course. Your document upload will correspond to your name automatically in Teams.**
 
 * If you have questions or concerns, please feel free to ask the instructor.

\newpage

1. Let $A$ and $B$ be events associated with the same sample space with probability $P$. Decide if the following statement is: always true, sometimes true, or never true, and provide explanations on why.

    a. If $P(A) = 1/3$ and $P(B) = 1/3$ then $P(A \cap B) = 1/2$.
    b. If $P(A) = 1/3$ and $P(B) = 1/3$ then $P(A \cup B) = 1/2.$
    c. If $P(A) = 1/2$, $P(B)= 1/2$ and $P(A \cap B) = 1/4$ then $P( A \cup B) =3/4$.
    
2. We flip a fair coin two times. The flips are independent. Remember, a fair coin lands on heads $H$ with probability 1/2 and tails (T) with probability 1/2. If the outcomes are the same (HH or TT) we win; otherwise we lose.

    a. What is the sample space?

    b. Define the following events:
    
        - A: The first coin comes up heads
        - B: The second coin comes up heads
        - C: The event we win.
    
    c. What is $P(A \cap B \cap C)$?

3. You receive 10 letters, 5 of them come in red envelopes and 5 of them in blue envelopes. You randomly shuffle them and place them in a stack. Let $A$ be the event that there is at least 1 blue envelope in the top three letters of the stack. What is $P(A)$? (Your answer should be accurate to 3 decimal places.)
