---
title: '**Calculus Review**'
subtitle: "Mini-Assignment 2022-08-30 - MTH 461 - Fall 2022"
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[RO,R]{MTH 461A - Fall 2022}
  \fancyfoot[CO,C]{}
  \fancyfoot[R]{\thepage}
  \usepackage{float}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
    keep_tex: true
urlcolor: blue
link-citations: yes
bibliography: references.bib
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\

**Instructions:**
 
 * Please provide complete solutions for each problem. If it involves mathematical computations, explanations, or analysis, please provide your reasoning or detailed solutions.
 
 * Note that some problems have multiple solutions or ways to solve it. Make sure that your solutions are clear enough to showcase your work and understanding of the material.
 
 * Creativity and collaborations are encouraged. Use all of the resources you have and what you need to complete the mini-assignment. Each student must take personal responsibility and submit their work individually. Please abide by the University of Portland Academic Honor Principle.
 
 * There are two ways you can write your answers, a: by handwriting (either physically or digitally), or b: by typing on a template document with file type options, which can be downloaded from the course website.
 
 * If you had handwritten your answers/solutions on a physical paper, make sure to label it properly and please scan your document using a scanner app for convenience. Suggestions: (1) ["Tiny Scanner" for Android](https://play.google.com/store/apps/details?id=com.appxy.tinyscanner&hl=en_US&gl=US){target="_blank"} or (2) ["Scanner App" for iOS](https://apps.apple.com/us/app/scanner-app-scan-pdf-document/id595563753){target="_blank"}.
 
 * **Please save your work as one pdf file, don't put your name in any part of the document, and submit it to the Teams Assignments for this course. Your document upload will correspond to your name automatically in Teams.**
 
 * If you have questions or concerns, please feel free to ask the instructor.

\newpage

This is a calculus-based probability & statistics class! As such, this first Mini-Assignment will be an opportunity for you to review problems from calculus.

1. Find the derivative of the following:

    a. $f(x) = 4 x^5 + 3 x^2 + x^{1/3}$
    b. $f(x) = \log(4x) - \log(2x)$


2. Find the critical points of $f(x) = 4 x^3 + 3 x^2$ and decide whether each is a maximum, minimum or point of inflection.


3. Find the points on the graph of $f(x) = \frac{1}{3} x^3 + x^2 - x - 1$ where the slope is:

    a. -1
    b. 2
    c. -2


4. Find the first three terms of the Taylor series for $f(x) = e^x$ centered at the point $x = 0$. 

Do you see a pattern? Write the formula for the full Taylor series centered at 0. There are two series you should know by heart. This is one of them!


5. Determine whether the following series converge or diverge. If they converge, determine its sum:

    a. $$\sum_{n = 1}^{\infty} \frac{(-4)^n}{9^n}.$$
    b. $$\sum_{n = 1}^{\infty} \frac{(-4)^{2n}}{3^n}.$$

(These series are geometric series! And this is the second type of series you should know by heart!)


6. Determine the value of the following integral:

$$\int_{-1}^{1} | x | dx.$$


7. Determine the value of the following integral:

$$ \int_{-\infty}^{\infty} x^2 e^{-x^2} dx.$$

Hint: You should remind yourself what integration by parts is and the following information will likely be useful:

$$\int_{-\infty}^{\infty} e^{-x^2} dx = \sqrt{\pi}.$$


8. Let $\lambda > 0$ by a fixed constant. Calculate

$$\int_{0}^{\infty} \lambda x e^{-\lambda x}dx.$$
