---
title: '**Calculus Review \textcolor{blue}{Solutions}**'
subtitle: "Mini-Assignment 2022-08-30 - MTH 461 - Fall 2022"
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[RO,R]{MTH 461A - Fall 2022}
  \fancyfoot[CO,C]{}
  \fancyfoot[R]{\thepage}
  \usepackage{float}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
    keep_tex: true
urlcolor: blue
link-citations: yes
bibliography: references.bib
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\

**Instructions:**
 
 * Please provide complete solutions for each problem. If it involves mathematical computations, explanations, or analysis, please provide your reasoning or detailed solutions.
 
 * Note that some problems have multiple solutions or ways to solve it. Make sure that your solutions are clear enough to showcase your work and understanding of the material.
 
 * Creativity and collaborations are encouraged. Use all of the resources you have and what you need to complete the mini-assignment. Each student must take personal responsibility and submit their work individually. Please abide by the University of Portland Academic Honor Principle.
 
 * There are two ways you can write your answers, a: by handwriting (either physically or digitally), or b: by typing on a template document with file type options, which can be downloaded from the course website.
 
 * If you had handwritten your answers/solutions on a physical paper, make sure to label it properly and please scan your document using a scanner app for convenience. Suggestions: (1) ["Tiny Scanner" for Android](https://play.google.com/store/apps/details?id=com.appxy.tinyscanner&hl=en_US&gl=US){target="_blank"} or (2) ["Scanner App" for iOS](https://apps.apple.com/us/app/scanner-app-scan-pdf-document/id595563753){target="_blank"}.
 
 * **Please save your work as one pdf file, don't put your name in any part of the document, and submit it to the Teams Assignments for this course. Your document upload will correspond to your name automatically in Teams.**
 
 * If you have questions or concerns, please feel free to ask the instructor.

\newpage

This is a calculus-based probability & statistics class! As such, this first Mini-Assignment will be an opportunity for you to review problems from calculus.

1. Find the derivative of the following:

    a. $f(x) = 4 x^5 + 3 x^2 + x^{1/3}$
    b. $f(x) = \log(4x) - \log(2x)$

\textcolor{blue}{\textbf{a.} This should be relatively straightforward because $f(x)$ is a polynomial.
$$f'(x) = 20 x^4 + 6 x + \frac{1}{3} x^{-2/3}.$$}

\textcolor{blue}{\textbf{b.} This is also straight forward if you remember $\log(x)' = \frac{1}{x}$ and the Chain rule.
$$\left(\log(4x) - \log(2x) \right)' =  4 \frac{1}{4x} - 2 \frac{1}{2x} = \frac{1}{x} - \frac{1}{x} = 0.$$}

\

2. Find the critical points of $f(x) = 4 x^3 + 3 x^2$ and decide whether each is a maximum, minimum or point of inflection.

\textcolor{blue}{The critical points are those points where the derivative of $f(x)$ is equal to 0.
$$f'(x) = 12 x^2 + 6x.$$}

\textcolor{blue}{The solutions to $f'(x) = 0$ are $x = 0$ and $x = \frac{-1}{2}$.  To determine if they are a minimum or maximum we need to find the second derivative of $f(x)$.
$$f''(x) = 24 x + 6.$$}

\textcolor{blue}{Plugging in we see that we have:
- $f''(0) = 6 > 0$ which means that $x = 0$ is a minimum.
- $f''\left( \frac{-1}{2} \right) = -6 < 0$ which means that $x = \frac{-1}{2}$ is a maximum.}

\textcolor{blue}{Don't forget to plug each of those points into the original function $f(x)$ to find their corresponding y-coordinates.}

\textcolor{blue}{An inflection point is a point in a graph at which the concavity changes. The second derivative is the go-to tool for concavity and inflection.}

\textcolor{blue}{Set the second derivative equal to zero and solve. There is one solution, $x=-\frac{1}{4}$. It is not necessarily going to be inflection point though! We have to find out how the concavity changes from interval to interval first.}

\textcolor{blue}{Let's set up a table to figure out what happens in each interval. Within each interval, choose a sample point to plug into $f''(x)$ to determine the concavity.}

\textcolor{blue}{\begin{tabular}{|c|c|c|c|}
\hline
Interval & Sample point $x$ & $f''(x)$ & Concavity \\
\hline
$(-\infty, -\frac{1}{4})$ & $-\frac{1}{2}$ & $6>0$ & Concave up \\
$(-\frac{1}{4}, \infty)$ & $0$ & $-6<0$ &  Concave down\\
\hline
\end{tabular}}

\textcolor{blue}{This confirms that $x = -\frac{1}{4}$ is an inflection point. However, $x = -\frac{1}{4}$ is not a critical point.}

\textcolor{blue}{To sum up, there are two critical points of $f(x)$, $(0, 0)$ (which is a minimum) and $(-\frac{1}{2}, \frac{1}{4})$ (which is a maximum).}

\

3. Find the points on the graph of $f(x) = \frac{1}{3} x^3 + x^2 - x - 1$ where the slope is:

    a. -1
    b. 2
    c. -2

\textcolor{blue}{This question is asking at what points of the graph (i.e., points $(x,f(x))$ ) is the derivative a particular value. So the first step is to take the derivative:
$$f'(x) = x^2 + 2 x - 1.$$}

\textcolor{blue}{\textbf{a.}
* $f'(x) = -1$ when 
$$ x^2 + 2x - 1 = -1 \implies x^2 + 2x = 0 \implies x = \{ 0 , -2\}.$$
Thus there are two points on the graph with this slope: 
$$(0, f(0)) = (0,-1) \text{ and }  (-2,f(-2)) = \left( -2, \frac{7}{3}\right).$$}

\textcolor{blue}{\textbf{b.}
* $f'(x) = 2$ when
$$ x^2 + 2x - 1 = 2 \implies x^2 + 2x - 3 = 0 \implies x = \{ 1 , -3\}.$$
Thus there are two points on the graph with this slope: 
$$(1, f(1)) = \left( 1,\frac{-2}{3} \right) \text{ and }  (-3,f(-3)) = ( -3,2).$$}

\textcolor{blue}{\textbf{c.}
* $f'(x) = -2$ when
$$ x^2 + 2x - 1 = -2 \implies x^2 + 2x + 1 = 0 \implies x = -1.$$
Thus there is only one point on the graph with this slope:
$$(-1, f(-1)) = \left( 1,\frac{2}{3} \right).$$}

\

4. Find the first three terms of the Taylor series for $f(x) = e^x$ centered at the point $x = 0$. 

Do you see a pattern? Write the formula for the full Taylor series centered at 0. There are two series you should know by heart. This is one of them!

\textcolor{blue}{We remember the Taylor Series centered around 0 is given by the following:
$$f(x) = \sum_{n = 0}^{\infty} \frac{f^{(n)}(0)}{n!} x^n$$
where $f^{(n)}(0)$ is the $n$-th derivative of $f(x)$ evaluated at $0$.}

\textcolor{blue}{Because $e^x$ is a magical function! We know $f^{(n)}(x) = f(x)$. As such, $$f^{(n)}(0) = f(0) = e^0 = 1.$$}

\textcolor{blue}{
Thus, the Taylor Series of $e^x$ centered as $x = 0$ is given by the following awesome formula:
$$e^{x} = \sum_{n = 0}^{\infty} \frac{x^n}{n!}.$$}

\

5. Determine whether the following series converge or diverge. If they converge, determine its sum:

    a. $$\sum_{n = 1}^{\infty} \frac{(-4)^n}{9^n}.$$
    b. $$\sum_{n = 1}^{\infty} \frac{(-4)^{2n}}{3^n}.$$

\textcolor{blue}{(These series are geometric series! And this is the second type of series you should know by heart!)}

\textcolor{blue}{Recall that a geometric series is of the form:
$$\sum_{n = 0}^{\infty} a r^n$$
where $a$ is a constant.}

\textcolor{blue}{We know that the sum of finitely many terms in the geometric series can be written as follows:
$$\sum_{n = 0}^{k-1} a r^n = a \left( \frac{1 - r^k}{1 - r}\right)$$}

\textcolor{blue}{The sum of a geometric series if finite if the expression $r$ is less than 1 in absolute value. Further the sum is given by:
$$\sum_{n = 0}^{\infty} a r^n = a \left( \frac{1}{1 - r}\right)$$}

\textcolor{blue}{When we start at the sum at $n = 1$ instead of $n = 0$, which is the case for both our examples, we have:
$$\sum_{n = 1}^{\infty} a r^n = a \left( \frac{r}{1 - r}\right)$$}

\textcolor{blue}{\textbf{a.}
$$\sum_{n = 1}^{\infty} \frac{(-4)^n}{9^n} = \sum_{n = 1}^{\infty} \left( \frac{-4}{9} \right)^n$$}

\textcolor{blue}{Since $| -4/9 | < 1$, this series converges and the sum is given by:
$$\frac{ \frac{-4}{9} }{1 - \frac{-4}{9}} = \frac{-4}{13}.$$}

\textcolor{blue}{\textbf{b.}
$$\sum_{n = 1}^{\infty} \frac{(-4)^{2n}}{3^n} = \sum_{n = 1}^{\infty} \left( \frac{(-4)^2}{3}\right)^n   = \sum_{n = 1}^{\infty} \left( \frac{16}{3} \right)^n.$$}

\textcolor{blue}{Since $16/3 > 1$, we know this series does not converge.}

\textcolor{blue}{(These series are geometric series! And this is the second type of series you should know by heart!)}

\

6. Determine the value of the following integral:

$$\int_{-1}^{1} | x | dx.$$

\textcolor{blue}{
\begin{eqnarray}
\int_{-1}^1 |x| dx & = & \int_{-1}^0 |x| dx + \int_{0}^{1} |x| dx \nonumber \\
                          & = & \int_{-1}^0 -x dx  + \int_{0}^{1} x dx \nonumber \\
                          & = & \frac{-1}{2} x^2 \Biggr|_{-1}^{0} + \frac{1}{2}  x^2 \Biggr|_{0}^{1} \nonumber \\
                          & = & \frac{-1}{2} \left( 0^2 - (-1)^2 \right) + \frac{1}{2} \left( 1^2 - 0^2 \right) = \frac{1}{2} + \frac{1}{2} = 1. \nonumber
\end{eqnarray}
}

\

7. Determine the value of the following integral:

$$ \int_{-\infty}^{\infty} x^2 e^{-x^2} dx.$$

Hint: You should remind yourself what integration by parts is and the following information will likely be useful:

$$\int_{-\infty}^{\infty} e^{-x^2} dx = \sqrt{\pi}.$$

\textcolor{blue}{We use the method of integration by parts to solve the above integral. Let $u=x$, $du=dx$, $dv=x e^{-x^{2}}dx$, and $v=\frac{-e^{-x^2}}{2}$.}

\textcolor{blue}{
\begin{eqnarray}
\int_{-\infty }^{\infty } x^2 \exp \left(-x^2\right) dx & = & \frac{-xe^{-x^2}}{2}\Biggr|_{-\infty}^{\infty} + \int_{-\infty}^{\infty} \frac{e^{-x^2}}{2}dx \nonumber \\
& = & 0 + \frac{\sqrt{\pi}}{2} \nonumber \\
& = & \frac{\sqrt{\pi}}{2}.\nonumber
\end{eqnarray}
}

\

8. Let $\lambda > 0$ by a fixed constant. Calculate

$$\int_{0}^{\infty} \lambda x e^{-\lambda x}dx.$$

\textcolor{blue}{We use the method of integration by parts to solve the above integral. Let $u=\lambda x$ and $dv=e^{-\lambda x} dx$. So, $du=\lambda dx$ and $v=-e^{-\lambda x}/\lambda$.}

\textcolor{blue}{
\begin{eqnarray}
\int_{0}^{\infty} \lambda x e^{-\lambda x} dx & = & \lambda x \left(-\frac{e^{-\lambda x}}{\lambda}\right)\Biggr|_{0}^{\infty} - \int_{0}^{\infty} \left(-\frac{e^{-\lambda x}}{\lambda}\right) \lambda dx \nonumber \\
 & = & -x e^{-\lambda x}\Biggr|_{0}^{\infty} + \int_{0}^{\infty} e^{-\lambda x} dx \nonumber \\
 & = & - x e^{-\lambda x}\Biggr|_{0}^{\infty} - \frac{1}{\lambda}e^{-\lambda x}\Biggr|_{0}^{\infty} \nonumber \\
 & = & -\lim_{x\to\infty} x e^{-\lambda x} + \lim_{x\to0} x e^{-\lambda x} - \lim_{x\to\infty}\frac{1}{\lambda}e^{-\lambda x} + \lim_{x\to0}\frac{1}{\lambda}e^{-\lambda x} \nonumber \\
 & = & -0 + 0 - 0 + \frac{1}{\lambda} \nonumber \\
 & = & \frac{1}{\lambda} \nonumber
\end{eqnarray}
}
