---
title: '**Probability Theory Basics Part 2 \textcolor{blue}{Solutions}**'
subtitle: "Mini-Assignment 2022-09-06 - MTH 461 - Fall 2022"
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[RO,R]{MTH 461A - Fall 2022}
  \fancyfoot[CO,C]{}
  \fancyfoot[R]{\thepage}
  \usepackage{float}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
    keep_tex: true
urlcolor: blue
link-citations: yes
bibliography: references.bib
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\

**Instructions:**
 
 * Please provide complete solutions for each problem. If it involves mathematical computations, explanations, or analysis, please provide your reasoning or detailed solutions.
 
 * Note that some problems have multiple solutions or ways to solve it. Make sure that your solutions are clear enough to showcase your work and understanding of the material.
 
 * Creativity and collaborations are encouraged. Use all of the resources you have and what you need to complete the mini-assignment. Each student must take personal responsibility and submit their work individually. Please abide by the University of Portland Academic Honor Principle.
 
 * There are two ways you can write your answers, a: by handwriting (either physically or digitally), or b: by typing on a template document with file type options, which can be downloaded from the course website.
 
 * If you had handwritten your answers/solutions on a physical paper, make sure to label it properly and please scan your document using a scanner app for convenience. Suggestions: (1) ["Tiny Scanner" for Android](https://play.google.com/store/apps/details?id=com.appxy.tinyscanner&hl=en_US&gl=US){target="_blank"} or (2) ["Scanner App" for iOS](https://apps.apple.com/us/app/scanner-app-scan-pdf-document/id595563753){target="_blank"}.
 
 * **Please save your work as one pdf file, don't put your name in any part of the document, and submit it to the Teams Assignments for this course. Your document upload will correspond to your name automatically in Teams.**
 
 * If you have questions or concerns, please feel free to ask the instructor.

\newpage

1. Consider a scenario where you roll a pair of six-sided fair dice *once*.

    a. How many possible outcomes are there? Make a table of all possible outcomes and make another table that sums the numbers of each possible outcome.
    b. What is the probability of rolling a (3,4) or (4,3) pair?
    c. What is the probability of rolling a sum of 8 or a sum of 6?
    d. What is the probability of rolling at least a sum of 5?
    e. What is the probability of rolling a 3 in either dice?
    f. What is the probability of rolling either dice has a maximum of 4?
    
\textcolor{blue}{\textbf{a.} Since there are six sides of each dice, then there are $6^2 = 36$ possible outcomes.}

|   |    1    |    2    |    3    |     4    |     5    |     6    |
|:-:|:-------:|:-------:|:-------:|:--------:|:--------:|:--------:|
| 1 | {1,1} 2 | {1,2} 3 | {1,3} 4 |  {1,4} 5 |  {1,5} 6 |  {1,6} 7 |
| 2 | {2,1} 3 | {2,2} 4 | {2,3} 5 |  {2,4} 6 |  {2,5} 7 |  {2,6} 8 |
| 3 | {3,1} 4 | {3,2} 5 | {3,3} 6 |  {3,4} 7 |  {3,5} 8 |  {3,6} 9 |
| 4 | {4,1} 5 | {4,2} 6 | {4,3} 7 |  {4,4} 8 |  {4,5} 9 | {4,6} 10 |
| 5 | {5,1} 6 | {5,2} 7 | {5,3} 8 |  {5,4} 9 | {5,5} 10 | {5,6} 11 |
| 6 | {6,1} 7 | {6,2} 8 | {6,3} 9 | {6,4} 10 | {6,5} 11 | {6,6} 12 |

\textcolor{blue}{\textbf{b.} $$P(\{3,4\}) + P(\{4,3\}) = \frac{1}{36} + \frac{1}{36} = \frac{2}{36} = \frac{1}{18}$$}

\textcolor{blue}{\textbf{c.} $$P(8) + P(6) = \frac{5}{36} + \frac{5}{36} = \frac{10}{36} = \frac{5}{18}$$}

\textcolor{blue}{\textbf{d.} 
\begin{align*}
\sum_{n=5}^{12} P(n) = & P(5) + P(6) + P(7) + P(8) + P(9) + P(10) + P(11) + P(12) \\
                     = & \frac{4}{36} + \frac{5}{36} + \frac{6}{36} + \frac{5}{36} + \frac{4}{36}+ \frac{3}{36} + \frac{2}{36} + \frac{1}{36} \\
                     = & \frac{30}{36} = \frac{5}{6}
\end{align*}}

\textcolor{blue}{\textbf{e.} 
\begin{align*}
P(\{*,3\}) + P(\{3,*\}) - P(\{3,3\}) = & \frac{6}{36} + \frac{6}{36} - \frac{1}{36} \\ 
                                     = & \frac{11}{36} \\
\end{align*}}

\textcolor{blue}{\textbf{f.} 
\begin{align*}
P(\{*,4\}) + P(\{4,*\}) - P(\{*,\ge 4\}) - P(\{\ge 4,*\}) + P(\{4,4\}) = & \frac{6}{36} + \frac{6}{36} - \frac{3}{36} - \frac{3}{36} + \frac{1}{36} \\
                                                                       = & \frac{7}{36} \\
\end{align*}}

\
    
2. Consider a scenario where you roll a pair of six-sided fair dice *twice*.

    a. How many possible outcomes are there? You don't have to make tables.
    b. What is the probability that the first roll has a sum of 6 and the second roll has a sum of 4?
    c. What is the probability of rolling a total sum of exactly 13?
    d. What is the probability of rolling that the total sum is at most 13?
    e. What is the probability of rolling exactly one 3 in any of the pairs?
    f. What is the probability of rolling at most 3 in any of the pairs?
    
\textcolor{blue}{\textbf{a.}
There are $36*36 = 1296$ possible outcomes.}

\textcolor{blue}{\textbf{b.} Note that each roll is independent but a roll with a pair of dice is not independent.
$$P_{\text{roll 1}}(6)P_{\text{roll 2}}(4) = \left(\frac{5}{36}\right)\left(\frac{3}{36}\right) = \frac{15}{1296} = \frac{5}{432}$$}
    
\textcolor{blue}{\textbf{c.} There are multiple ways that we can get a sum of 13 using a pair of dice rolled twice.
\begin{align*}
  P(13) = & 2P_{roll 1}(11)P_{roll 2}(2) + \\
          & 2P_{roll 1}(10)P_{roll 2}(3) + \\
          & 2P_{roll 1}(9)P_{roll 2}(4) + \\
          & 2P_{roll 1}(8)P_{roll 2}(5) + \\
          & 2P_{roll 1}(7)P_{roll 2}(6) \\
        = & 2 \left(\frac{2}{36}\right)\left(\frac{1}{36}\right) + \\
          & 2 \left(\frac{3}{36}\right)\left(\frac{2}{36}\right) + \\
          & 2 \left(\frac{4}{36}\right)\left(\frac{3}{36}\right) + \\
          & 2 \left(\frac{5}{36}\right)\left(\frac{4}{36}\right) + \\
          & 2 \left(\frac{6}{36}\right)\left(\frac{5}{36}\right) + \\
        = & \frac{70}{1296}
\end{align*}}

\textcolor{blue}{\textbf{d.}
\begin{align*}
  P(\le 13) = & \sum_{n=4}^{13} 2P(n) \\
            = & 2\left(P(4) + P(5) + P(6) + P(7) + P(8) + P(9) + P(10) + P(11) + P(12) + P(13)\right) \\
            = & 2\big(P_{roll 1}(2)P_{roll 2}(2) + \\
              & P_{roll 1}(2)P_{roll 2}(3) + \\
              & P_{roll 1}(3)P_{roll 2}(3) + P_{roll 1}(4)P_{roll 2}(2) + \\
              & P_{roll 1}(4)P_{roll 2}(3) + P_{roll 1}(5)P_{roll 2}(2) + \\
              & P_{roll 1}(4)P_{roll 2}(4) + P_{roll 1}(5)P_{roll 2}(3) + P_{roll 1}(6)P_{roll 2}(6) + \\
              & P_{roll 1}(5)P_{roll 2}(4) + P_{roll 1}(6)P_{roll 2}(3) + P_{roll 1}(7)P_{roll 2}(2) + \\
              & P_{roll 1}(5)P_{roll 2}(5) + P_{roll 1}(6)P_{roll 2}(4) + P_{roll 1}(7)P_{roll 2}(3) + P_{roll 1}(8)P_{roll 2}(2) + \\
              & P_{roll 1}(6)P_{roll 2}(5) + P_{roll 1}(7)P_{roll 2}(4) + P_{roll 1}(8)P_{roll 2}(3) + P_{roll 1}(9)P_{roll 2}(2) + \\
              & P_{roll 1}(7)P_{roll 2}(5) + P_{roll 1}(8)P_{roll 2}(4) + P_{roll 1}(9)P_{roll 2}(3) + P_{roll 1}(10)P_{roll 2}(2) + \\
              & P_{roll 1}(11)P_{roll 2}(2) + P_{roll 1}(10)P_{roll 2}(3) + P_{roll 1}(9)P_{roll 2}(4) + P_{roll 1}(8)P_{roll 2}(5) + P_{roll 1}(7)P_{roll 2}(6)\big) \\
            = & \frac{316}{1296}\\
\end{align*}}

\textcolor{blue}{\textbf{e.} Let $A_1$ and $A_2$ be the event where pair 1 and pair 2 has exactly one 3. For one pair, there are 10 cases where there is exactly one 3.
\begin{align*}
  P(A_1)P(A_2^C) + P(A_1^C)P(A_2) = & \left(\frac{10}{36}\right) \left(1-\frac{10}{36}\right) + \left(1-\frac{10}{36}\right) \left(\frac{10}{36}\right) \\
                                  = & \frac{13}{324}\\
\end{align*}}

\textcolor{blue}{\textbf{f.} Let $B_1$ and $B_2$ be 1st and 2nd roll events where one of the pair of dice lands on at most three respectively.
\begin{align*}
  P(B_1)P(B_2^C) + P(B_1^C)P(B_2) = & \left(\frac{9}{36}\right)\left(1 - \frac{9}{36}\right) + \left(1 - \frac{9}{36}\right)\left(\frac{9}{36}\right) \\
                                  = & \frac{3}{8}\\
\end{align*}}
