---
title: '**Law of Total Probability for CRVs**'
subtitle: "Mini-Assignment 2022-11-08 - MTH 461 - Fall 2022"
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[RO,R]{MTH 461A - Fall 2022}
  \fancyfoot[CO,C]{}
  \fancyfoot[R]{\thepage}
  \usepackage{float}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
    keep_tex: true
urlcolor: blue
link-citations: yes
bibliography: references.bib
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\

**Instructions:**
 
 * Please provide complete solutions for each problem. If it involves mathematical computations, explanations, or analysis, please provide your reasoning or detailed solutions.
 
 * Note that some problems have multiple solutions or ways to solve it. Make sure that your solutions are clear enough to showcase your work and understanding of the material.
 
 * Creativity and collaborations are encouraged. Use all of the resources you have and what you need to complete the mini-assignment. Each student must take personal responsibility and submit their work individually. Please abide by the University of Portland Academic Honor Principle.
 
 * There are two ways you can write your answers, a: by handwriting (either physically or digitally), or b: by typing on a template document with file type options, which can be downloaded from the course website.
 
 * If you had handwritten your answers/solutions on a physical paper, make sure to label it properly and please scan your document using a scanner app for convenience. Suggestions: (1) ["Tiny Scanner" for Android](https://play.google.com/store/apps/details?id=com.appxy.tinyscanner&hl=en_US&gl=US){target="_blank"} or (2) ["Scanner App" for iOS](https://apps.apple.com/us/app/scanner-app-scan-pdf-document/id595563753){target="_blank"}.
 
 * **Please save your work as one pdf file, don't put your name in any part of the document, and submit it to the Teams Assignments for this course. Your document upload will correspond to your name automatically in Teams.**
 
 * If you have questions or concerns, please feel free to ask the instructor.

\newpage
  
1. Suppose $X \sim Uniform(a,b)$ where $a = 1$ and $b = 2$, and given $X = x$, $Y$ is an exponential random variable with parameter $\lambda = x$, so we can write $Y|X \sim Exponential(x)$.

    Recall that the pdf of a continuous uniform distribution is given by
    $$f_X(x) = 
    \begin{cases}
    \frac{1}{b-a} &, for a \le x \le b \\
    0   &, \text{otherwise}
    \end{cases}$$
    and also recall that given $Y \sim Exponential(\lambda)$, then the pdf is given by
    $$f_Y(y) = \lambda e^{-\lambda y}, \text{ for } \lambda > 0,$$
    and then $E[Y] = \frac{1}{\lambda}$ and $Var(Y) = \frac{1}{\lambda^2}$.

    a. Find $E[Y]$ using the law of total expectation.
    b. Find $Var(Y)$ using the law of total variance.
    c. Find $P(X + Y > 1)$ using the law of total probability. Set-up the integral in its simplest form and do not solve.

2. Consider $X \sim Exponential(\lambda)$ where $\lambda = 1$, and given $X = x$. Suppose that $Y$ is a normal random variable with parameters $\mu = x$ and $\sigma = 1$, so we can write $Y|X \sim Normal(x,1)$.

    Recall that the pdf of an exponential distribution is given by
    $$f_X(x) = \lambda e^{-\lambda x}, \text{ for } \lambda > 0$$
    and also given $Y \sim Normal(\mu,\sigma)$, then the pdf is given by
    $$f_Y(y) = \frac{1}{\sigma \sqrt{2 \pi}} e^{-\frac{1}{2}\left( \frac{y-\mu}{\sigma} \right)^2}$$
    and then $E[Y] = \mu$ and $Var(Y) = \sigma^2$.

    a. Find $E[Y]$ using the law of total expectation.
    b. Find $Var(Y)$ using the law of total variance.
    c. Find $P(X + Y > 1)$ using the law of total probability. Set-up the integral in its simplest form and do not solve.