---
title: '**Moment Generating Functions for CRVs**'
subtitle: "Mini-Assignment 2022-11-15 - MTH 461 - Fall 2022"
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[RO,R]{MTH 461A - Fall 2022}
  \fancyfoot[CO,C]{}
  \fancyfoot[R]{\thepage}
  \usepackage{float}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
    keep_tex: true
urlcolor: blue
link-citations: yes
bibliography: references.bib
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\

**Instructions:**
 
 * Please provide complete solutions for each problem. If it involves mathematical computations, explanations, or analysis, please provide your reasoning or detailed solutions.
 
 * Note that some problems have multiple solutions or ways to solve it. Make sure that your solutions are clear enough to showcase your work and understanding of the material.
 
 * Creativity and collaborations are encouraged. Use all of the resources you have and what you need to complete the mini-assignment. Each student must take personal responsibility and submit their work individually. Please abide by the University of Portland Academic Honor Principle.
 
 * There are two ways you can write your answers, a: by handwriting (either physically or digitally), or b: by typing on a template document with file type options, which can be downloaded from the course website.
 
 * If you had handwritten your answers/solutions on a physical paper, make sure to label it properly and please scan your document using a scanner app for convenience. Suggestions: (1) ["Tiny Scanner" for Android](https://play.google.com/store/apps/details?id=com.appxy.tinyscanner&hl=en_US&gl=US){target="_blank"} or (2) ["Scanner App" for iOS](https://apps.apple.com/us/app/scanner-app-scan-pdf-document/id595563753){target="_blank"}.
 
 * **Please save your work as one pdf file, don't put your name in any part of the document, and submit it to the Teams Assignments for this course. Your document upload will correspond to your name automatically in Teams.**
 
 * If you have questions or concerns, please feel free to ask the instructor.

\newpage
  
1. Let $X$ and $Y$ be two independent random variables with respective moment generating functions 
$$M_X(s) = \frac{1}{1-5s}, \text{ if } s < \frac{1}{5}, \text{ and }$$
$$M_Y(s) = \frac{1}{(1-5s)^2}, \text{ if } s < \frac{1}{5}.$$
Find $E[(X+Y)^2]$.

2. Suppose $X$ and $Y$ are independent Poisson random variables with parameters $\lambda_x$, $\lambda_y$, respectively. Find the distribution of $X + Y$. (Hint: Find the Joint MGF first, and then match the results to known MGFs.)

    Recall that the mgf for a Poisson random variable is given by
    $$M_x(s) = e^{\lambda (e^s - 1)}$$
    where $\lambda$ is the parameter of the Poisson pmf.

3. True or False? If $X \sim Exponential(\lambda_x)$ and $Y \sim Exponential(\lambda_y)$ then $X + Y \sim Exponential(\lambda_x + \lambda_y)$. Justify your answer. (Hint: Find MGF of $X + Y$, and see if it matches with the MGFs of $X$ and $Y$.)

    Recall that the mgf for an Exponential random variable is given by
    $$M_X(s) = \frac{\lambda}{\lambda - s}$$
    where $\lambda$ is the parameter of the Exponential pdf.
    