---
title: "Mini-Projects"
subtitle: "Fall 2022 - University of Portland"
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[RO,R]{MTH 461 Probability \& Statistics I - Syllabus}
  \fancyfoot[CO,C]{}
  \fancyfoot[R]{\thepage}
  \usepackage{float}
output:
  bookdown::pdf_document2:
    toc: yes
    number_section: no
urlcolor: blue
link-citations: yes
---

<br>

This semester, we will focus on two distinct topics. The case studies below are guided projects meaning instructions, problem sets, and open-ended questions are provided.

<br>

## **Learning Objectives**

There are three main objectives for this project, which is in line with the learning objectives of MTH 461 course:

1. To learn skills in data acumen, wrangling, and visualization.
2. To learn effective and concise communication of data.
3. To learn new and existing methods and to hone independent learning.

Each mini-project will be evaluated according to the above objectives and the learning outcomes outlined in the Syllabus.

<br>

## **Case Studies**

*Note: The case studies are tentative and may change throughout the course.*

<br>

### Case Study 1: Linguistic Patterns in Published Books and News Articles

TBW

<br>

### Case Study 2: The State of The US State Crimes

TBW

<br>

